name: Deploy to GitHub Pages
run-name: ${{ github.actor }} is deploying to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BASE_PATH: '/wuxing-calendar/'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set environment and install dependencies
        uses: ./.github/actions/prepare

      - name: Build WASM 📦
        run: just wasm-build

      - name: Re-link WASM package
        run: pnpm install

      - name: Build web 📦
        working-directory: web
        run: pnpm exec vite build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './web/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
